# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Miguel
tagline:          'was here'
description:      'Another try for making a website for my thoughts. Posting in English and sometimes in Spanish. Made by <a href="https://twitter.com/miguelglhf" target="_blank">@miguelglhf</a> using <a href="http://jekyllrb.com" target="_blank">Jekyll</a> and <a href="http://lanyon.getpoole.com" target="_blank">Poole+Lanyon</a>.'
url:              
baseurl:          '/'
paginate:         5

author:
  name:           'Miguel Gallego'
  url:            https://twitter.com/miguelglhf

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
